databases:
  - name: instant_search
    databaseName: instant_search_production
    user: instant_search
    plan: free

services:
  - type: web
    name: instant-search
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec rails s"
    plan: free
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: instant_search
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
